credential:
  bundles:
    keystore:
      K0:
        location: file:/container/signkey.p12
        password: changeit
        type: JKS
      K1:
        location: file:/container/signkey.p12
        password: changeit
        type: JKS
    jks:
      VK:
        store-reference: K0
        name: "VK"
      SK:
        store-reference: K0
        name: "SK"


openid:
  federation:
    storage: memory
    registry:
      integration:
        enabled: false
        validation-keys:
          - VK
    sign:
      - SK

spring:
  ssl:
    bundle:
      jks:
        oidf-internal:
          truststore:
            location: file:container/truststore.p12
            password: changeit
            type: PKCS12
