on:
  workflow_call:
    inputs:
      release-to-github:
        type: boolean
        required: false
        default: false
      release-to-maven-central:
        type: boolean
        required: false
        default: false
      revision-property:
        type: string
        default: revision
      requires-private-dependencies:
        type: boolean
        default: false
        description: Required if any dependency is only uploaded to github mvn repository

jobs:
  mvn-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Set Maven version from tag name
        if: startsWith(github.ref, 'refs/tags/')
        env:
          REVISION_PROPERTY: ${{ inputs.revision-property }}
          TAG: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.SC_ACTION_SECRET }}
        run: |
          echo "TAG:$TAG"
          NEW_VERSION=${TAG#v}
          echo "New version is $NEW_VERSION"
          mvn versions:set-property -DgenerateBackupPoms=false -Dproperty=$REVISION_PROPERTY \
          -DnewVersion=$NEW_VERSION --no-transfer-progress

      - if: ${{ inputs.requires-private-dependencies == true }}
        name: Install dependencies
        run: mvn clean install -DskipTests=true --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ secrets.SC_ACTION_SECRET }}

      - run: mvn --batch-mode deploy --no-transfer-progress
        name: Deploy maven artifacts
        if: ${{ inputs.release-to-github == true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
      - run: echo "Release to maven central is not implemented"
        if: ${{ inputs.release-to-maven-central == true }}
