name: Automated publication of docker image
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    uses: swedenconnect/openid-federation-commons/.github/workflows/resuable-mvn-publish.yml@main
    secrets: inherit
    with:
      auto-update-revision: true
