# Sets the revision property to the current tagged version
on:
  workflow_call:
    inputs:
      revision-property:
        type: string
        required: false
        default: revision

jobs:
  mvn-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: |
          new_version=`echo $tag | awk -F'v' '{print $2}'`
          echo "New version is $new_version"
          mvn versions:set-property -DgenerateBackupPoms=false -Dproperty=${{inputs.revision-property}} -DnewVersion=$new_version --no-transfer-progress
        env:
          tag: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.SC_ACTION_SECRET }}