on:
  workflow_call:
    inputs:
      release-to-github:
        type: boolean
        required: false
        default: false
      release-to-maven-central:
        type: boolean
        required: false
        default: false

jobs:
  mvn-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Set version
        run: |
          new_version=`echo $tag | awk -F'v' '{print $2}'`
          echo "New version is $new_version"
          mvn versions:set-property -DgenerateBackupPoms=false -Dproperty=${{inputs.revision-property}} -DnewVersion=$new_version --no-transfer-progress
        env:
          tag: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.SC_ACTION_SECRET }}
      - run: mvn --batch-mode deploy --no-transfer-progress
        if: ${{ inputs.release-to-github == true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
      - run: echo "Release to maven central is not implemented"
        if: ${{ inputs.release-to-maven-central == true }}
