name: Automated release of maven artifacts
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    uses: swedenconnect/openid-federation-commons/.github/workflows/reusable-mvn-release.yml@main
    secrets: inherit
    with:
      auto-update-revision: true
