name: Automated release of maven libraries
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  prepare:
    uses: swedenconnect/openid-federation-commons/.github/workflows/mvn-artifact-version-prepare.yml@workflow
    secrets: inherit
    with:
      revision-property: service-revision
  release:
    uses: swedenconnect/openid-federation-commons/.github/workflows/mvn-release.yml@workflow
    secrets: inherit
    with:
      revision-property: service-revision
      release-to-github: true
      release-to-maven-central: false
  finalize:
    uses: swedenconnect/openid-federation-commons/.github/workflows/finalize.yml@workflow
    secrets: inherit
    with:
      auto-update-revision: true
      revision-property: revision

