on:
  workflow_call:
    inputs:
      auto-update-revision:
        type: boolean
        required: false
        default: false

jobs:
  mvn-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: mvn versions:set-property -DgenerateBackupPoms=false -Dproperty=revision -DnewVersion=`echo $tag | awk -F'v' '{print $2}'` --no-transfer-progress
        env:
          tag: ${{ github.ref_name }}
      - run: mvn --batch-mode deploy --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
  gh-release:
    needs:
      - mvn-release
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
  version-update:
    needs:
      - gh-release
    name: Update reversion version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - if: ${{ inputs.auto-update-revision == true }}
        name: Commits changes and pushes
        run: |
          next_snapshot_version=`echo $tag | awk -F'[v.]' '{printf "%s.%s.%s-SNAPSHOT",$2,$3,$4+1}'`
          mvn versions:set-property -Dproperty=revision -DnewVersion=$next_snapshot_version -DgenerateBackupPoms=false
          # Github Actions user
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git status
          git commit -m "Update to next snapshot version"
          git push
        env:
          tag: ${{ github.ref_name }}
