name: Automated release of maven snapshot libraries
on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'
jobs:
  release:
    uses: swedenconnect/openid-federation-commons/.github/workflows/mvn-release.yml@main
    secrets: inherit
    with:
      revision-property: service-revision
      release-to-github: true
      release-to-maven-central: false
  finalize:
    needs: release
    uses: swedenconnect/openid-federation-commons/.github/workflows/finalize.yml@main
    secrets: inherit
    with:
      auto-update-revision: true
      revision-property: revision

